import { normalizeOverlay, type OverlayField } from "./overlay-settings";
export const drzDefaults = {
  delta_smooth: 3,
  pivot_length: 12,
  pivot_source: "Cumulative Delta",
  roc_length: 12,
  impulse_window: 100,
  atr_length: 14,
  atr_multiplier: 0.35,
  maximum_zones: 8,
  merge_zones: true,
  merge_gap_ticks: 20,
  lower_zone_color: "#00ff00",
  upper_zone_color: "#ff0000",
  show_zone_boxes: true,
  show_signals: true,
  extend_bars: 65,
  stats_box_bars: 30,
  tick_size: 0,
};
export type DrzParams = typeof drzDefaults;
export const drzFields: OverlayField[] = [
  {
    key: "delta_smooth",
    label: "Delta Smoothing Length (EMA)",
    group: "Delta Settings",
    kind: "number",
    default: 3,
    min: 1,
    max: 4000,
    step: 1,
  },
  {
    key: "pivot_length",
    label: "Pivot Length (Left/Right)",
    group: "Delta Settings",
    kind: "number",
    default: 12,
    min: 2,
    max: 4000,
    step: 1,
  },
  {
    key: "pivot_source",
    label: "Pivot Source",
    group: "Delta Settings",
    kind: "choice",
    default: "Cumulative Delta",
    options: ["Cumulative Delta", "Cumulative Delta RoC"],
  },
  {
    key: "roc_length",
    label: "RoC Length (if RoC selected)",
    group: "Delta Settings",
    kind: "number",
    default: 12,
    min: 2,
    max: 4000,
    step: 1,
  },
  {
    key: "impulse_window",
    label: "Impulse Window Length",
    group: "Delta Settings",
    kind: "number",
    default: 100,
    min: 5,
    max: 4000,
    step: 1,
  },
  {
    key: "atr_length",
    label: "ATR Length",
    group: "Zone Construction",
    kind: "number",
    default: 14,
    min: 1,
    max: 4000,
    step: 1,
  },
  {
    key: "atr_multiplier",
    label: "ATR Multiplier",
    group: "Zone Construction",
    kind: "number",
    default: 0.35,
    min: 0.01,
    max: 4000,
    step: 0.05,
  },
  {
    key: "maximum_zones",
    label: "Maximum Zones Displayed",
    group: "Zone Construction",
    kind: "number",
    default: 8,
    min: 5,
    max: 200,
    step: 1,
  },
  {
    key: "merge_zones",
    label: "Merge Overlapping Zones",
    group: "Zone Construction",
    kind: "boolean",
    default: true,
  },
  {
    key: "merge_gap_ticks",
    label: "Merge Gap (in ticks)",
    group: "Zone Construction",
    kind: "number",
    default: 20,
    min: 0.0,
    max: 4000,
    step: 10,
  },
  {
    key: "lower_zone_color",
    label: "Support Color",
    group: "Visualization",
    kind: "color",
    default: "#00ff00",
  },
  {
    key: "upper_zone_color",
    label: "Resistance Color",
    group: "Visualization",
    kind: "color",
    default: "#ff0000",
  },
  {
    key: "show_zone_boxes",
    label: "Show Zone Boxes",
    group: "Visualization",
    kind: "boolean",
    default: true,
  },
  {
    key: "show_signals",
    label: "Show Signals",
    group: "Visualization",
    kind: "boolean",
    default: true,
  },
  {
    key: "extend_bars",
    label: "Extend Zone (bars)",
    group: "Zone Construction",
    kind: "number",
    default: 65,
    min: 0,
    max: 600,
    step: 1,
  },
  {
    key: "stats_box_bars",
    label: "Stats Box Width (bars)",
    group: "Visualization",
    kind: "number",
    default: 30,
    min: 1,
    max: 50,
    step: 1,
  },
  {
    key: "tick_size",
    label: "Размер тика (0 — автоматически)",
    group: "Zones",
    kind: "number",
    default: 0,
    min: 0,
    max: 100000,
    step: 1e-8,
  },
];
export const normalizeDrzParams = (raw: unknown): DrzParams =>
  normalizeOverlay(drzFields, raw);
