import { normalizeOverlay, type OverlayField } from "./overlay-settings";
export const smcDefaults = {
  modeInput: "Historical",
  styleInput: "Colored",
  showTrendInput: false,
  showInternalsInput: true,
  showInternalBullInput: "All",
  internalBullColorInput: "#089981",
  showInternalBearInput: "All",
  internalBearColorInput: "#F23645",
  internalFilterConfluenceInput: false,
  internalStructureSize: "tiny",
  showStructureInput: true,
  showSwingBullInput: "All",
  swingBullColorInput: "#089981",
  showSwingBearInput: "All",
  swingBearColorInput: "#F23645",
  swingStructureSize: "small",
  showSwingsInput: false,
  swingsLengthInput: 50,
  showHighLowSwingsInput: true,
  showInternalOrderBlocksInput: true,
  internalOrderBlocksSizeInput: 5,
  showSwingOrderBlocksInput: false,
  swingOrderBlocksSizeInput: 5,
  orderBlockFilterInput: "Atr",
  orderBlockMitigationInput: "High/Low",
  internalBullishOrderBlockColor: "#3179f5",
  internalBearishOrderBlockColor: "#f77c80",
  swingBullishOrderBlockColor: "#1848cc",
  swingBearishOrderBlockColor: "#b22833",
  showEqualHighsLowsInput: true,
  equalHighsLowsLengthInput: 3,
  equalHighsLowsThresholdInput: 0.1,
  equalHighsLowsSizeInput: "tiny",
  showFairValueGapsInput: false,
  fairValueGapsThresholdInput: true,
  fairValueGapsTimeframeInput: "Chart",
  fairValueGapsBullColorInput: "#00ff68",
  fairValueGapsBearColorInput: "#ff0008",
  fairValueGapsExtendInput: 1,
  showDailyLevelsInput: false,
  dailyLevelsStyleInput: "Solid",
  dailyLevelsColorInput: "#2157f3",
  showWeeklyLevelsInput: false,
  weeklyLevelsStyleInput: "Solid",
  weeklyLevelsColorInput: "#2157f3",
  showMonthlyLevelsInput: false,
  monthlyLevelsStyleInput: "Solid",
  monthlyLevelsColorInput: "#2157f3",
  showPremiumDiscountZonesInput: false,
  premiumZoneColorInput: "#F23645",
  equilibriumZoneColorInput: "#878b94",
  discountZoneColorInput: "#089981",
  mtfMode: "confirmed",
};
export type SmcParams = typeof smcDefaults;
export const smcFields: OverlayField[] = [
  {
    key: "modeInput",
    label: "Mode",
    group: "Smart Money Concepts",
    kind: "choice",
    default: "Historical",
    options: ["Historical", "Present"],
  },
  {
    key: "styleInput",
    label: "Style",
    group: "Smart Money Concepts",
    kind: "choice",
    default: "Colored",
    options: ["Colored", "Monochrome"],
  },
  {
    key: "showTrendInput",
    label: "Color Candles",
    group: "Smart Money Concepts",
    kind: "boolean",
    default: false,
  },
  {
    key: "showInternalsInput",
    label: "Show Internal Structure",
    group: "Real Time Internal Structure",
    kind: "boolean",
    default: true,
  },
  {
    key: "showInternalBullInput",
    label: "Bullish Structure",
    group: "Real Time Internal Structure",
    kind: "choice",
    default: "All",
    options: ["All", "BOS", "CHoCH"],
  },
  {
    key: "internalBullColorInput",
    label: "Internal bull color",
    group: "Real Time Internal Structure",
    kind: "color",
    default: "#089981",
  },
  {
    key: "showInternalBearInput",
    label: "Bearish Structure",
    group: "Real Time Internal Structure",
    kind: "choice",
    default: "All",
    options: ["All", "BOS", "CHoCH"],
  },
  {
    key: "internalBearColorInput",
    label: "Internal bear color",
    group: "Real Time Internal Structure",
    kind: "color",
    default: "#F23645",
  },
  {
    key: "internalFilterConfluenceInput",
    label: "Confluence Filter",
    group: "Real Time Internal Structure",
    kind: "boolean",
    default: false,
  },
  {
    key: "internalStructureSize",
    label: "Internal Label Size",
    group: "Real Time Internal Structure",
    kind: "choice",
    default: "tiny",
    options: ["tiny", "small", "normal"],
  },
  {
    key: "showStructureInput",
    label: "Show Swing Structure",
    group: "Real Time Swing Structure",
    kind: "boolean",
    default: true,
  },
  {
    key: "showSwingBullInput",
    label: "Bullish Structure",
    group: "Real Time Swing Structure",
    kind: "choice",
    default: "All",
    options: ["All", "BOS", "CHoCH"],
  },
  {
    key: "swingBullColorInput",
    label: "Swing bull color",
    group: "Real Time Swing Structure",
    kind: "color",
    default: "#089981",
  },
  {
    key: "showSwingBearInput",
    label: "Bearish Structure",
    group: "Real Time Swing Structure",
    kind: "choice",
    default: "All",
    options: ["All", "BOS", "CHoCH"],
  },
  {
    key: "swingBearColorInput",
    label: "Swing bear color",
    group: "Real Time Swing Structure",
    kind: "color",
    default: "#F23645",
  },
  {
    key: "swingStructureSize",
    label: "Swing Label Size",
    group: "Real Time Swing Structure",
    kind: "choice",
    default: "small",
    options: ["tiny", "small", "normal"],
  },
  {
    key: "showSwingsInput",
    label: "Show Swings Points",
    group: "Real Time Swing Structure",
    kind: "boolean",
    default: false,
  },
  {
    key: "swingsLengthInput",
    label: "Swings length",
    group: "Real Time Swing Structure",
    kind: "number",
    default: 50,
    min: 10,
    max: 4000,
    step: 1,
  },
  {
    key: "showHighLowSwingsInput",
    label: "Show Strong/Weak High/Low",
    group: "Real Time Swing Structure",
    kind: "boolean",
    default: true,
  },
  {
    key: "showInternalOrderBlocksInput",
    label: "Internal Order Blocks",
    group: "Order Blocks",
    kind: "boolean",
    default: true,
  },
  {
    key: "internalOrderBlocksSizeInput",
    label: "Internal order blocks size",
    group: "Order Blocks",
    kind: "number",
    default: 5,
    min: 1,
    max: 20,
    step: 1,
  },
  {
    key: "showSwingOrderBlocksInput",
    label: "Swing Order Blocks",
    group: "Order Blocks",
    kind: "boolean",
    default: false,
  },
  {
    key: "swingOrderBlocksSizeInput",
    label: "Swing order blocks size",
    group: "Order Blocks",
    kind: "number",
    default: 5,
    min: 1,
    max: 20,
    step: 1,
  },
  {
    key: "orderBlockFilterInput",
    label: "Order Block Filter",
    group: "Order Blocks",
    kind: "choice",
    default: "Atr",
    options: ["Atr", "Cumulative Mean Range"],
  },
  {
    key: "orderBlockMitigationInput",
    label: "Order Block Mitigation",
    group: "Order Blocks",
    kind: "choice",
    default: "High/Low",
    options: ["Close", "High/Low"],
  },
  {
    key: "internalBullishOrderBlockColor",
    label: "Internal Bullish OB",
    group: "Order Blocks",
    kind: "color",
    default: "#3179f5",
  },
  {
    key: "internalBearishOrderBlockColor",
    label: "Internal Bearish OB",
    group: "Order Blocks",
    kind: "color",
    default: "#f77c80",
  },
  {
    key: "swingBullishOrderBlockColor",
    label: "Bullish OB",
    group: "Order Blocks",
    kind: "color",
    default: "#1848cc",
  },
  {
    key: "swingBearishOrderBlockColor",
    label: "Bearish OB",
    group: "Order Blocks",
    kind: "color",
    default: "#b22833",
  },
  {
    key: "showEqualHighsLowsInput",
    label: "Equal High/Low",
    group: "EQH/EQL",
    kind: "boolean",
    default: true,
  },
  {
    key: "equalHighsLowsLengthInput",
    label: "Bars Confirmation",
    group: "EQH/EQL",
    kind: "number",
    default: 3,
    min: 1,
    max: 4000,
    step: 1,
  },
  {
    key: "equalHighsLowsThresholdInput",
    label: "Threshold",
    group: "EQH/EQL",
    kind: "number",
    default: 0.1,
    min: 0,
    max: 0.5,
    step: 0.1,
  },
  {
    key: "equalHighsLowsSizeInput",
    label: "Label Size",
    group: "EQH/EQL",
    kind: "choice",
    default: "tiny",
    options: ["tiny", "small", "normal"],
  },
  {
    key: "showFairValueGapsInput",
    label: "Fair Value Gaps",
    group: "Fair Value Gaps",
    kind: "boolean",
    default: false,
  },
  {
    key: "fairValueGapsThresholdInput",
    label: "Auto Threshold",
    group: "Fair Value Gaps",
    kind: "boolean",
    default: true,
  },
  {
    key: "fairValueGapsTimeframeInput",
    label: "Timeframe",
    group: "Fair Value Gaps",
    kind: "choice",
    default: "Chart",
    options: ["Chart", "15m", "30m", "1h", "2h", "4h", "8h", "12h", "1d"],
  },
  {
    key: "fairValueGapsBullColorInput",
    label: "Bullish FVG",
    group: "Fair Value Gaps",
    kind: "color",
    default: "#00ff68",
  },
  {
    key: "fairValueGapsBearColorInput",
    label: "Bearish FVG",
    group: "Fair Value Gaps",
    kind: "color",
    default: "#ff0008",
  },
  {
    key: "fairValueGapsExtendInput",
    label: "Extend FVG",
    group: "Fair Value Gaps",
    kind: "number",
    default: 1,
    min: 0,
    max: 4000,
    step: 1,
  },
  {
    key: "showDailyLevelsInput",
    label: "Daily",
    group: "Highs & Lows MTF",
    kind: "boolean",
    default: false,
  },
  {
    key: "dailyLevelsStyleInput",
    label: "Daily levels style",
    group: "Highs & Lows MTF",
    kind: "choice",
    default: "Solid",
    options: ["Solid", "Dashed", "Dotted"],
  },
  {
    key: "dailyLevelsColorInput",
    label: "Daily levels color",
    group: "Highs & Lows MTF",
    kind: "color",
    default: "#2157f3",
  },
  {
    key: "showWeeklyLevelsInput",
    label: "Weekly",
    group: "Highs & Lows MTF",
    kind: "boolean",
    default: false,
  },
  {
    key: "weeklyLevelsStyleInput",
    label: "Weekly levels style",
    group: "Highs & Lows MTF",
    kind: "choice",
    default: "Solid",
    options: ["Solid", "Dashed", "Dotted"],
  },
  {
    key: "weeklyLevelsColorInput",
    label: "Weekly levels color",
    group: "Highs & Lows MTF",
    kind: "color",
    default: "#2157f3",
  },
  {
    key: "showMonthlyLevelsInput",
    label: "Monthly",
    group: "Highs & Lows MTF",
    kind: "boolean",
    default: false,
  },
  {
    key: "monthlyLevelsStyleInput",
    label: "Monthly levels style",
    group: "Highs & Lows MTF",
    kind: "choice",
    default: "Solid",
    options: ["Solid", "Dashed", "Dotted"],
  },
  {
    key: "monthlyLevelsColorInput",
    label: "Monthly levels color",
    group: "Highs & Lows MTF",
    kind: "color",
    default: "#2157f3",
  },
  {
    key: "showPremiumDiscountZonesInput",
    label: "Premium/Discount Zones",
    group: "Premium & Discount Zones",
    kind: "boolean",
    default: false,
  },
  {
    key: "premiumZoneColorInput",
    label: "Premium Zone",
    group: "Premium & Discount Zones",
    kind: "color",
    default: "#F23645",
  },
  {
    key: "equilibriumZoneColorInput",
    label: "Equilibrium Zone",
    group: "Premium & Discount Zones",
    kind: "color",
    default: "#878b94",
  },
  {
    key: "discountZoneColorInput",
    label: "Discount Zone",
    group: "Premium & Discount Zones",
    kind: "color",
    default: "#089981",
  },
  {
    key: "mtfMode",
    label: "Данные старшего ТФ",
    group: "Fair Value Gaps",
    kind: "choice",
    default: "confirmed",
    options: ["confirmed", "pine"],
  },
];
export const normalizeSmcParams = (raw: unknown): SmcParams =>
  normalizeOverlay(smcFields, raw);
